In [17]:
a = 1; print(type(a))

<class 'int'>


run시키면 각 cell의 마지막 줄만 run 되니까 cell의 내용을 다 표시하도록 실행시키기 위해서는 print(a), print(b) 이렇게 하면 됨.  
type()은 변수의 class를 알려줌. int stands for integer (정수) 

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


float는 소수점있는 것. 

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


a는 1.2로 float이어야하는데 바로 뒤에 a=int(a)를 통해 a를 정수처리하고, 이는 1.2에서 소수점을 뺀 수. 당연히 정수의 type를 출력하면 output으로 int 가 나옴. 

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


a[]는 대괄호안에 지정된 숫자에 따라 그 숫자에 상응하는 순번의 값을 취할 수 있게 해줌. ex. a='123'일때 a[0]=1, a[1]=2, a[2]=a[-1]=3. 
str은 ''로 표현, 이 ''안의 숫자는 사칙연산이 불가능

In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


list는 대괄호안에 ',' 로 분리가 되어있는것. 안의 내용이 꼭 숫자일 필요없고 
a= [1, 2, 'ab'] 이런식으로 해도 list (확장이 엄청나게 가능)

In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


tuple은 대괄호가 아닌 ()로 표현. list와 비슷하긴 하지만 바꾸기가 더 어려움. 

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


dict stands for dictionary. dict는 대괄호나 소괄호가아닌 {}를 사용.
':'과 ""를 통해 meaning을 assign 한다고 생각하면 될 것 같음. 

In [1]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

위 상태는 그냥 list에 불과한데 밑의 cell과 같이 'array'를 쓰면 matrix 비슷하게 b가 array화 되고, 그렇게 되면 아래와 같은 결과가 나옴. 결과가 나오는데 시간을 걸리는건 "import"이라는 걸 하는데 시간이 걸리기 때문 . 
그래서 위의 list와 달리 아래는 뭔가 행렬느낌이 남. (n dimensional array가 됨)

In [6]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


python에서 행렬을 사용하기위해서는 'numpy'를 사용함. 
import: python이 basic하게 가지고 있지 않은고 하드디스크에 다운받아놓은 걸 메모리로 올려놓은것. 여태 import을 사용하지 않았던건 여태 쓴 함수들은 기본적으로 가지고 있던것이기 때문. numpy는 그렇지 않기 때문에 띄워놓으려고 import 사용. 
numpy는 directory의 모든 것을 메모리로 띄우라는 의미. 
뒤의 'as np'는 안써도 괜찮은데 말을 쉽고 편하게 쓰기 위해 저렇게 표현. numpy를 np로 줄여놓으면 그 뒤에 나올 내용을 b=np.array(a)처럼 편하게 쓸 수 있음. b=np.array(a)는 np(numpy)폴더 내의 array라는 함수를 쓰자 라는 말.
= 쉽게말해 필요한 함수들이 어디에 있는지 알고 import를 해서, 그 밑에 있는 function array를 쓰기 위해 저렇게 써야함. 
(numpy라는 폴더 안에는 엄청나게 많은 함수이 있어 자주 쓰이는데 그때마다 numpy라고 쓰지않고 as np 라고 설정. => np.array ) 

In [29]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


b* b 를 하면 2x3행렬과 2x3행렬을 곱하는 꼴이니 실질적으로는 계산이 안되는게 정상인데 어떻게 결과가나오는거냐? 를 물어본다면
array는 사실, 정확히 따지면 행렬이 아니고 형태만 행렬과 비슷한것이기 때문에 곱셈이 단순 element by element로 연산이 되어버린것. 

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


np 안에는 matrix라는 함수도 있는데 그 안에 b 를 넣었더니 c가 나오고, 이걸 출력해보면 위와 같이 보이지만 class를 보면 진짜 matrix가 되었다는걸 알 수 있음. (unlike array)

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

c는 이제 진짜 행렬이니까 c* c 가 곱해지지 않는것. 그 이유가 error 이유로 나와있음. 

In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

t는 transpose. transpose를 하면 2x3 => 3x2 이니까 이제 연산이 되는것. 이 함수도 numpy안에 있음.

참고) numpy는 python의 library 중 가장 중요한 것이라고 할 수 있음. 

In [3]:
s='abcdef'

In [4]:
type(s)

str

In [5]:
print(type(s))

<class 'str'>
